/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestResultRouteImport } from './routes/test.result'
import { Route as TestInfoRouteImport } from './routes/test.info'
import { Route as TestStepRouteImport } from './routes/test.$step'
import { Route as AdminTestResultsRouteImport } from './routes/admin.test-results'
import { Route as AdminTestQuestionsRouteImport } from './routes/admin.test-questions'
import { Route as AdminTestAnalyticsRouteImport } from './routes/admin.test-analytics'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPersonalityTypesRouteImport } from './routes/admin.personality-types'
import { Route as AdminPageRouteImport } from './routes/admin.page'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestResultRoute = TestResultRouteImport.update({
  id: '/test/result',
  path: '/test/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TestInfoRoute = TestInfoRouteImport.update({
  id: '/test/info',
  path: '/test/info',
  getParentRoute: () => rootRouteImport,
} as any)
const TestStepRoute = TestStepRouteImport.update({
  id: '/test/$step',
  path: '/test/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestResultsRoute = AdminTestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestQuestionsRoute = AdminTestQuestionsRouteImport.update({
  id: '/test-questions',
  path: '/test-questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestAnalyticsRoute = AdminTestAnalyticsRouteImport.update({
  id: '/test-analytics',
  path: '/test-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalityTypesRoute = AdminPersonalityTypesRouteImport.update({
  id: '/personality-types',
  path: '/personality-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/page': typeof AdminPageRoute
  '/admin/personality-types': typeof AdminPersonalityTypesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/test-analytics': typeof AdminTestAnalyticsRoute
  '/admin/test-questions': typeof AdminTestQuestionsRoute
  '/admin/test-results': typeof AdminTestResultsRoute
  '/test/$step': typeof TestStepRoute
  '/test/info': typeof TestInfoRoute
  '/test/result': typeof TestResultRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/page': typeof AdminPageRoute
  '/admin/personality-types': typeof AdminPersonalityTypesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/test-analytics': typeof AdminTestAnalyticsRoute
  '/admin/test-questions': typeof AdminTestQuestionsRoute
  '/admin/test-results': typeof AdminTestResultsRoute
  '/test/$step': typeof TestStepRoute
  '/test/info': typeof TestInfoRoute
  '/test/result': typeof TestResultRoute
  '/admin': typeof AdminIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/page': typeof AdminPageRoute
  '/admin/personality-types': typeof AdminPersonalityTypesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/test-analytics': typeof AdminTestAnalyticsRoute
  '/admin/test-questions': typeof AdminTestQuestionsRoute
  '/admin/test-results': typeof AdminTestResultsRoute
  '/test/$step': typeof TestStepRoute
  '/test/info': typeof TestInfoRoute
  '/test/result': typeof TestResultRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/events'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/page'
    | '/admin/personality-types'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/test-analytics'
    | '/admin/test-questions'
    | '/admin/test-results'
    | '/test/$step'
    | '/test/info'
    | '/test/result'
    | '/admin/'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/events'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/page'
    | '/admin/personality-types'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/test-analytics'
    | '/admin/test-questions'
    | '/admin/test-results'
    | '/test/$step'
    | '/test/info'
    | '/test/result'
    | '/admin'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/events'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/page'
    | '/admin/personality-types'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/test-analytics'
    | '/admin/test-questions'
    | '/admin/test-results'
    | '/test/$step'
    | '/test/info'
    | '/test/result'
    | '/admin/'
    | '/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TestStepRoute: typeof TestStepRoute
  TestInfoRoute: typeof TestInfoRoute
  TestResultRoute: typeof TestResultRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/test/result': {
      id: '/test/result'
      path: '/test/result'
      fullPath: '/test/result'
      preLoaderRoute: typeof TestResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/info': {
      id: '/test/info'
      path: '/test/info'
      fullPath: '/test/info'
      preLoaderRoute: typeof TestInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$step': {
      id: '/test/$step'
      path: '/test/$step'
      fullPath: '/test/$step'
      preLoaderRoute: typeof TestStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/test-results': {
      id: '/admin/test-results'
      path: '/test-results'
      fullPath: '/admin/test-results'
      preLoaderRoute: typeof AdminTestResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-questions': {
      id: '/admin/test-questions'
      path: '/test-questions'
      fullPath: '/admin/test-questions'
      preLoaderRoute: typeof AdminTestQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-analytics': {
      id: '/admin/test-analytics'
      path: '/test-analytics'
      fullPath: '/admin/test-analytics'
      preLoaderRoute: typeof AdminTestAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personality-types': {
      id: '/admin/personality-types'
      path: '/personality-types'
      fullPath: '/admin/personality-types'
      preLoaderRoute: typeof AdminPersonalityTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/page': {
      id: '/admin/page'
      path: '/page'
      fullPath: '/admin/page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPageRoute: typeof AdminPageRoute
  AdminPersonalityTypesRoute: typeof AdminPersonalityTypesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminTestAnalyticsRoute: typeof AdminTestAnalyticsRoute
  AdminTestQuestionsRoute: typeof AdminTestQuestionsRoute
  AdminTestResultsRoute: typeof AdminTestResultsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPageRoute: AdminPageRoute,
  AdminPersonalityTypesRoute: AdminPersonalityTypesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminTestAnalyticsRoute: AdminTestAnalyticsRoute,
  AdminTestQuestionsRoute: AdminTestQuestionsRoute,
  AdminTestResultsRoute: AdminTestResultsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TestStepRoute: TestStepRoute,
  TestInfoRoute: TestInfoRoute,
  TestResultRoute: TestResultRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
